---
kind: pipline
name: bazel_cc

platform:
  os: linux
  arch: amd64

steps:
- name: docker_bazel_cc
  image: plugins/docker
  settings:
    context: ./bazel_cc
    dockerfile: ./bazel_cc/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/bazel_cc
    username:
      from_secret: quay_username

---
kind: pipline
name: go

platform:
  os: linux
  arch: amd64

steps:
- name: docker_go
  image: plugins/docker
  settings:
    context: ./go
    dockerfile: ./go/Dockerfile
    password:
      from_secret: quay_password
    registry: quay.io
    repo: quay.io/jonnrb/go
    username:
      from_secret: quay_username

...
